server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: kobe
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 指定Druid连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${kobe.datasource.host}:${kobe.datasource.port}/${kobe.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${kobe.datasource.username}
    password: ${kobe.datasource.password}

redis:
  host: localhost
  port: 6379
  password:  # Redis密码（没有则留空）
  database: 0



